services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "root" # Should change to strong Token Id
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    privileged: true
    command: server -dev # Run in Dev Mode
    networks:
      - vault-app

networks:
  vault-app:
    external: true
    name: vault-app